USE DATABASE SNOWFLAKE_SAMPLE_DATA;

DESC TABLE TPCDS_SF100TCL.STORE_SALES;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB; 

CREATE SCHEMA IF NOT EXISTS BRONZE;

CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAW AS 
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 5000000000;

select count(*) as total_records
from BRONZE.STORE_SALES_RAW;

DESC TABLE BRONZE.STORE_SALES_RAW;

SELECT 
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(SS_SALES_PRICE) AS NON_NULL_SALES_PRICE,
FROM BRONZE.STORE_SALES_RAW;

SELECT 
    MIN(SS_SOLD_DATE_SK) AS MIN_SOLD_DATE_SK,
    MAX(SS_SOLD_DATE_SK) AS MAX_SOLD_DATE_SK
FROM BRONZE.STORE_SALES_RAW;

SELECT 
    MIN(SS_SALES_PRICE) AS MIN_SALES_PRICE,
    MAX(SS_SALES_PRICE) AS MAX_SALES_PRICE
FROM BRONZE.STORE_SALES_RAW;